repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.1.4
    hooks:
      - id: sqlfluff-fix
        args: [--dialect, postgres]
      - id: sqlfluff-lint
        args: [--dialect, postgres]