version: '3.8'
services:
  database:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # mount the create tables script for the postgres container to auto run.
      - ./bootstrap_schema.sql:/docker-entrypoint-initdb.d/bootstrap_schema.sql
      # mount for the tables to be populated
      - ./bootstrap_data.sql:/docker-entrypoint-initdb.d/bootstrap_data.sql
