version: '3.8'
services:
  database:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./01_bootstrap_schema.sql:/docker-entrypoint-initdb.d/01_bootstrap_schema.sql
      # copy the sql script to fill tables
      - ./02_bootstrap_data.sql:/docker-entrypoint-initdb.d/02_bootstrap_data.sql